Repository Qiskit/qiskit-ignis, pull requests merged in 2020-09, with the labels that each got.

#486 Drop support for Python 3.5
  .github/workflows/main.yml
  releasenotes/notes/drop-py35-1a7810120bfa3bef.yaml
  setup.py
  tox.ini
Labels: Changelog: Removal

#482 Correct QVFitter confidence level threshold to 0.977
  qiskit/ignis/verification/quantum_volume/fitters.py
  releasenotes/notes/fix-qv-threshold-fcb0c8dce22fefa5.yaml
Labels: Changelog: Bugfix, stable-backport-potential

#492 fixed but different seed for each qubit in RB seed
  qiskit/ignis/verification/randomized_benchmarking/circuits.py
  releasenotes/notes/rb-seed-fix-24957ed1e9ffe31c.yaml
  test/rb/generate_data.py
  test/rb/test_fitter_cnotdihedral_X_results.json
  test/rb/test_fitter_cnotdihedral_Z_results.json
  test/rb/test_fitter_cnotdihedral_expected_results.json
  test/rb/test_fitter_coherent_purity_expected_results.json
  test/rb/test_fitter_coherent_purity_results.json
  test/rb/test_fitter_expected_results_1.json
  test/rb/test_fitter_expected_results_2.json
  test/rb/test_fitter_interleaved_expected_results.json
  test/rb/test_fitter_interleaved_results.json
  test/rb/test_fitter_original_results.json
  test/rb/test_fitter_purity_expected_results.json
  test/rb/test_fitter_purity_results.json
  test/rb/test_fitter_results_1.json
  test/rb/test_fitter_results_2.json
Labels: Changelog: Bugfix, stable-backport-potential

#500 Add expectation value measurement error mitigation
  README.md
  qiskit/ignis/mitigation/__init__.py
  qiskit/ignis/mitigation/expval/__init__.py
  qiskit/ignis/mitigation/expval/base_meas_mitigator.py
  qiskit/ignis/mitigation/expval/circuits.py
  qiskit/ignis/mitigation/expval/complete_mitigator.py
  qiskit/ignis/mitigation/expval/ctmp_fitter.py
  qiskit/ignis/mitigation/expval/ctmp_generator_set.py
  qiskit/ignis/mitigation/expval/ctmp_mitigator.py
  qiskit/ignis/mitigation/expval/fitter.py
  qiskit/ignis/mitigation/expval/tensored_mitigator.py
  qiskit/ignis/mitigation/expval/utils.py
  qiskit/ignis/mitigation/measurement/circuits.py
  qiskit/ignis/mitigation/measurement/filters.py
  qiskit/ignis/mitigation/measurement/fitters.py
  qiskit/ignis/numba.py
  qiskit/ignis/verification/tomography/data.py
  releasenotes/notes/expval-meas-mit-0f3d97311ef80aa9.yaml
  setup.py
  test/measurement/discriminator/test_iq_discriminator.py
  test/mitigation/__init__.py
  test/mitigation/test_assignment_matrices.py
  test/mitigation/test_markov.py
  test/mitigation/test_mitigators.py
Labels: Changelog: New Feature
