Repository Qiskit/qiskit-ignis, pull requests merged in 2020-06, with the labels that each got.

#415 Add README as pypi long description
  MANIFEST.in
  setup.py
Labels: stable-backport-potential

#420 Raising error when incompatible inputs are passed to mitigation
  qiskit/ignis/mitigation/measurement/filters.py
  releasenotes/notes/mitigtion-label-error-137dd0acfdcfc5f6.yaml
Labels: Changelog: Bugfix, stable-backport-potential

#422 Fix issues with CVXPY default solvers
  .travis.yml
  azure-pipelines.yml
  qiskit/ignis/verification/tomography/fitters/base_fitter.py
  qiskit/ignis/verification/tomography/fitters/cvx_fit.py
Labels: Changelog: Bugfix, stable-backport-potential

#425 Rework trigger logic in azure-pipelines
  azure-pipelines.yml
Labels: stable-backport-potential

#427 Revert accidental breaking backports
  azure-pipelines.yml
  docs/conf.py
  qiskit/ignis/VERSION.txt
  qiskit/ignis/measurement/discriminator/filters.py
  qiskit/ignis/mitigation/measurement/filters.py
  qiskit/ignis/verification/accreditation/fitters.py
  tox.ini
Labels: Changelog: Bugfix

#431 Fix fitter selection logic in process tomography
  qiskit/ignis/verification/tomography/fitters/process_fitter.py
  requirements-dev.txt
  tox.ini
Labels: stable-backport-potential

#435 [Stable] Fix fitter selection logic in process tomography (#431)
  qiskit/ignis/verification/tomography/fitters/process_fitter.py
  requirements-dev.txt
  tox.ini
Labels: Changelog: Bugfix

#436 Add scikit-learn dependency and add CI job without optional dependencies
  .travis.yml
  releasenotes/notes/missing-dependency-e7c99c7751bcd162.yaml
  setup.py
  test/tomography/test_process_tomography.py
  test/tomography/test_state_tomography.py
  tox.ini
Labels: Changelog: Bugfix, stable-backport-potential

#439 [Stable] Add scikit-learn dependency and add CI job without optional dependencies (#436)
  .travis.yml
  releasenotes/notes/missing-dependency-e7c99c7751bcd162.yaml
  setup.py
  test/tomography/test_process_tomography.py
  test/tomography/test_state_tomography.py
  tox.ini
Labels: Changelog: Bugfix

#438 fixed partial trace constraint in cvx fitting routine
  qiskit/ignis/verification/tomography/fitters/cvx_fit.py
Labels: Changelog: Bugfix, stable-backport-potential

#440 [Stable] Fixed partial trace constraint in cvx fitting routine (#438)
  qiskit/ignis/verification/tomography/fitters/cvx_fit.py
Labels: Changelog: Bugfix
